@operixBaseUrl = http://localhost:5236/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkYW5pc2hAZXhhbXBsZS5jb20iLCJleHAiOjE3ODc0OTkwNTIsImlzcyI6Ik9wZXJpeCIsImF1ZCI6Ik9wZXJpeC5BcGkifQ.FO9dRTqgS9ccKgFcinlCuKF9C3ZUJ0aJuIVo0H4EdcA

### Create Organization
POST {{operixBaseUrl}}/organizations
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "ABC Manufacturing",
    "code": "ABC"
}


### Get Organization by ID
GET {{operixBaseUrl}}/organizations/1
Accept: application/json
Authorization: Bearer {{accessToken}}


### Get All Organizations
GET {{operixBaseUrl}}/organizations
Accept: application/json


### Update Organization
PUT {{operixBaseUrl}}/organizations/1
Content-Type: application/json
Accept: application/json

{
    "name": "ABC Manufacturing Updated",
    "code": "ABC",
    "isActive": true
}


### Delete Organization
DELETE {{operixBaseUrl}}/organizations/1
Accept: application/json





### Create Department
POST {{operixBaseUrl}}/departments
Content-Type: application/json
Accept: application/json

{
    "organizationId": 1,
    "parentDepartmentId": null,
    "name": "Maintenance",
    "code": "MAINTENANCE"
}

###

### Get Department
GET {{operixBaseUrl}}/departments/1
Accept: application/json

###

### Get All Departments
GET {{operixBaseUrl}}/departments?organizationId=1
Accept: application/json

###

### Update Department
PUT {{operixBaseUrl}}/departments/1
Content-Type: application/json
Accept: application/json

{
    "parentDepartmentId": null,
    "name": "Maintenance",
    "code": "MAINTENANCE",
    "isActive": true
}

###

### Delete Department
DELETE {{operixBaseUrl}}/departments/2
Accept: application/json


### Duplicate Department Code
POST {{operixBaseUrl}}/departments
Content-Type: application/json
Accept: application/json

{
    "organizationId": 1,
    "parentDepartmentId": null,
    "name": "Maintenance Duplicate",
    "code": "MAINTENANCE"
}


### Same Department Code - Different Organization
POST {{operixBaseUrl}}/departments
Content-Type: application/json
Accept: application/json

{
    "organizationId": 2,
    "parentDepartmentId": null,
    "name": "Maintenance",
    "code": "MAINTENANCE"
}

### Invalid Organization
POST {{operixBaseUrl}}/departments
Content-Type: application/json
Accept: application/json

{
    "organizationId": 99999,
    "parentDepartmentId": null,
    "name": "Production",
    "code": "PRODUCTION"
}

### Invalid Parent Department
POST {{operixBaseUrl}}/departments
Content-Type: application/json
Accept: application/json

{
    "organizationId": 1,
    "parentDepartmentId": 99999,
    "name": "Production",
    "code": "PRODUCTION"
}


### Parent From Different Organization
POST {{operixBaseUrl}}/departments
Content-Type: application/json
Accept: application/json

{
    "organizationId": 1,
    "parentDepartmentId": 2,
    "name": "Production",
    "code": "PRODUCTION"
}

### Department Cannot Be Its Own Parent
PUT {{operixBaseUrl}}/departments/1
Content-Type: application/json
Accept: application/json

{
    "parentDepartmentId": 1,
    "name": "Maintenance",
    "code": "MAINTENANCE",
    "isActive": true
}



### Create User
POST {{operixBaseUrl}}/users
Content-Type: application/json
Accept: application/json

{
    "organizationId": 1,
    "departmentId": null,
    "firstName": "Danish",
    "lastName": "Malak",
    "email": "danish@example.com",
    "password": "Test@123"
}


### Login
POST {{operixBaseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "danish@example.com",
    "password": "Test@123"
}

### Login - Invalid Password
POST {{operixBaseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "danish@example.com",
    "password": "WrongPassword"
}
